name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and test
        uses: docker/build-push-action@v5
        with:
          context: .
          target: test
          load: true
      -
        name: Sanitize repo name
        uses: actions/github-script@v6
        id: sanitize_repo_name
        with:
          result-encoding: string
          script: return '${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}'.toLowerCase()
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          #context: .
          push: true
          target: prod
          tags: ${{ steps.sanitize_repo_name.outputs.result }}:latest
